// <auto-generated />
using System;
using Chart_RazorP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chart_RazorP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chart_RazorP.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("185fbb20-0891-43ea-b4fc-f72eb27264a0"),
                            Address = "Chandigarh",
                            Name = "Sushant",
                            Salary = 45000
                        },
                        new
                        {
                            Id = new Guid("79929112-3952-4aa9-b8f6-688888189295"),
                            Address = "Mohali",
                            Name = "Nikhil",
                            Salary = 50000
                        },
                        new
                        {
                            Id = new Guid("f9ed439a-1960-4412-9d89-5a4246175ac5"),
                            Address = "Chandigarh",
                            Name = "Rohit",
                            Salary = 37000
                        },
                        new
                        {
                            Id = new Guid("aadc6818-76e6-491f-9a1e-172cd9524077"),
                            Address = "Chandigarh",
                            Name = "Uvti",
                            Salary = 27000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
